#!/usr/bin/env bash
#a comment

if [ "${1}" == "start" ]
then
	./manage_my_process &
	touch /var/run/my_process.pid
	echo "$!" > /var/run/my_process.pic
	echo "manage_my_process started"

elif [ "${1} == "stop" ]
then
	echo "manage_my_process stopped"
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid

elif [ "${1}" == "restart" ]
then
	kill "$(car /var/run/my_process.pid)"
	rm /var/run/my_process.pic
	./manage_my_process.pid
	echo "$!" > .var.run.my_process.pic
	echo "manage_my_process restarted"

else
	echo "Usage: manage_process {start|stop|restart}"
fi
